### ISSUE TITLE
Parse individualCount from preparations

### ISSUE THREAD

**Issue by laurarussell** [VertNet/toolkit#10]
I think it would be great sometime to be able to parse individualCount from preparations on the Specify generated collections.  Especially Fish, when the count is usually more than 1.

**Comment by tucotuco** [comment]
Do you think that is actually possible, given that the preparations provide a list of parts, each with a count?

Is there a specific case in which this would work?

**Comment by laurarussell** [comment]
Too many records with multiple prep types and counts to be feasible.  Closing as won't fix.
