### ISSUE TITLE
verbatimEventDate when year is missing

### ISSUE THREAD

**Issue by dbloom** [VertNet/toolkit#13]
@tucotuco We've reviewed the ISM Mammals migrator and we do not see any obvious, or not so obvious, issues with the current set of queries.

Taking just one dataset as an example, here are the ISM Mammal catalog numbers in question: 617910, 617911, 615203, 616892, 617662.

E.g, 617910 - vertbatimEventDate is "4 May"   In SimpleDwCforVertNet eventDate is populating as "2016-05" and year is populating "2016", month is "5", and day is Null.

verbatimEventDate is the only date field in the source data.  As far as Laura and I can tell this may be a scenario we have not accounted for yet.  I mapped LegacyDates and it's doing everything else correctly.

iDigBio link provided by Meredith for Mammals is https://www.idigbio.org/portal/recordsets/17969b7f-c1d0-4c84-9cbc-de64b90a62a5
Migrator "Migrator_ISMMammals_v2015-11-25_DONE is archived at iPlant.

**Comment by tucotuco** [comment]
Fixed in d081d5ef6541e6fe19c1ac04915d3087f3219b1b
