### ISSUE TITLE
year is null when eventDate=year

### ISSUE THREAD

**Issue by laurarussell** [VertNet/toolkit#14]
When eventDate contains a year value only and verbatimEventDate is null, the year field is not populated.

When eventDate contains a year value only and verbatimeEventDate also contains that year value, then the year field is populated.

See VMNHForVertNet\invertpaleo for data.  Let me know if you need a copy of the migrator.

**Comment by tucotuco** [comment]
Fixed in d081d5ef6541e6fe19c1ac04915d3087f3219b1b
