### ISSUE TITLE
Parsing query for associatedMedia

### ISSUE THREAD

**Issue by laurarussell** [VertNet/toolkit#15]
Need query (or queries) to parse associatedMedia links into multiple records for inclusion in AudubonCore extension.

See GSU data and migrator.

Migrator is 46MB currently in VertNetAdmin dropbox.

Migrator-GSU-Herps-v2015-11-15-lar.zip

**Comment by laurarussell** [comment]
@tucotuco I figured this out for GSU.  Created a module function.  Also requires a MediaTemplate table, a Media table, a qryMedia query, and two items added to the macro.  Let me know the best way to give to you to incorporate into the main template.

**Comment by laurarussell** [comment]
Note: must make sure DAO is turned on in References in MS Access.

**Comment by dbloom** [comment]
Did I mention that this is awesome?

**Comment by tucotuco** [comment]
Added to the toolkit template in 17acada3a87be980ff938c94447c1153ff068c41.
