### ISSUE TITLE
Add ResourceRelationship Extension

### ISSUE THREAD

**Issue by laurarussell** [VertNet/toolkit#16]
Add ResourceRelationship Extension process for when resources are switching from urn format to a guid.

Example:  occurrenceID synched at GBIF and iDigBio is in urn format
urn:catalog:AUM:Fish:62637
resource is now in Specify and wants to use Specify collectionobject.guid and has provided it in data.  

In order to facilitate easy switch at GBIF and iDigBio we need to include resourceRelationship extension with the following terms:

occurrenceID (= new occurrenceID)
relatedResourceID (= old urn occurrenceID)
relationshipOfResource (= sameAs)

Thinking the new query to append data to the resourceRelationship table will pull new occurrenceID from simpleDwc and with contain the concatenation to construct the old urn occurrenceID.

**Comment by laurarussell** [comment]
BTW, I'm doing this work currently for AUM fish and am basing it on how you did Audubon Core Extension.  So could potentially copy/clean up my work from the AUM Fish Migrator.

**Comment by tucotuco** [comment]
This has been implemented in d56ddc35b06c7ab17bcb73e5e3f43d83ed77be26.
