### ISSUE TITLE
Change report format

### ISSUE THREAD

**Issue by laurarussell** [VertNet/toolkit#17]
Consider changing report output format from csv to txt.  Many institutions have difficulty with the csv opening in Excel and Excel interpreting values incorrectly.  If the reports format was changed to txt, we could include the instructions (http://vertnet.org/resources/downloadsinexcelguide.html) for opening txt files in Excel which would allow them to set encoding and set Excel to open all the fields as text.

**Comment by dbloom** [comment]
I like this idea because it would save us time on the support end of things.

**Comment by tucotuco** [comment]
Changed all reports except "Report - missing catalogNumber", "Report - StatsDifferences", and "Report - StatsCompleteness" to use export specifications and to output .txt files instead of csv files.

Resolved in e59c94c7966d2c3b440bd998e3d3223363eff5ae.
