### ISSUE TITLE
Add Plants template

### ISSUE THREAD

**Issue by laurarussell** [VertNet/toolkit#20]
Add a plants template please :-)

**Comment by tucotuco** [comment]
Added in commit 5926d6db4a6c4bde61e29ac0ab9cb5784433753f.

**Comment by laurarussell** [comment]
Need to add PlantsDwC2.mdb in workspace folder and add support for plants table, append query and macro in Aggregator template.

**Comment by tucotuco** [comment]
Done in commit 16e16128f0c3fa0924e56f53c04ff3b28e4eeeab. Note this is a major version change. Previous migrators are not compatible with the new vocabularies.
