### ISSUE TITLE
Curly vs straight quote/tick marks in coordinates

### ISSUE THREAD

**Issue by dbloom** [VertNet/toolkit#33]
Per example from SIO Marine Verts, queries for LegacyCoordinate processing 13 and 14 need to be updated to the below for the next version of the migrator.

13
Trim(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace([lat],"¦"," "),"Sud","S"),"Nord","N"),"MIN"," "),"DEG"," "),"?"," "),",",", "),":",""),"S",""),"N",""),"°"," "),"'"," "),"’"," "),'"'," ")," .","."),"(",""),")",""),"N"," N"),"S"," S"),"  "," "),"d"," "),"m",""),"-",""),"_"," "),"  "," "))

14
Trim(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace(Replace([lng],"¦"," "),"Oest","W"),"Est","E"),"MIN"," "),"DEG"," "),"?"," "),",",", "),":",""),"E",""),"W",""),"°"," "),"'"," "),"’"," "),'"'," ")," .","."),"(",""),")",""),"N"," N"),"S"," S"),"  "," "),"d"," "),"m",""),"-",""),"_"," "),"S",""),"  "," "))

**Comment by tucotuco** [comment]
Fixed in commit 3c9db748e315e7c3e98d76419d7241af01d46323.
