### ISSUE TITLE
Add URI to 'reference' field when null

### ISSUE THREAD

**Issue by mkoo** [VertNet/toolkit#7]
Create the URL portal.vertnet.org/o/[instiution_code]/[collection]?id=[catalog_no] ...  so that users can land on the vertnet specimen detail page, especially useful for 3rd party portals.

Also, noted that JW recommends using 'references' field for URLs to original specimen detail page

**Comment by tucotuco** [comment]
Added processing to create references field for the VertNet portal in 909658c6cf05d3ee9f238c1c9b82134d0a484a5d.
