### ISSUE TITLE
Revise reporting sequence in Macro

### ISSUE THREAD

**Issue by laurarussell** [VertNet/toolkit#8]
Edit Do DwC2 Migration so that it includes steps for only one generic set of reports. Use specific .bat files to rename the reports after they been produced and after the macro is finished.  Note:  removing the extra report sequences will alleviate memory issues in newer versions of Access.

**Comment by tucotuco** [comment]
Done in 4e3f4a1cbb35e472e7f990c2c444dc0e0691c06e.
