### ISSUE TITLE
Migrator Readme edit

### ISSUE THREAD

**Issue by laurarussell** [VertNet/toolkit#9]
Step 30 - a macro by that name doesn't exist.  There is one called, "1) Get and Check Local Vocabularies"

30) Open the database .\source\VertNetVocabulariesManager.mdb and run the macro "Check Vocabularies". This will open windows showing new terms that haven't been resolved yet in the vocabulary manager.

**Comment by tucotuco** [comment]
Fixed in 4e3f4a1cbb35e472e7f990c2c444dc0e0691c06e.
